[[main]]
name = "Blog"
url = "/all/"
identifier = "9ZEIG7GoKx"
weight = 1

[[main]]
name = "Tags"
parent = "More"
pageRef = "tags"
weight = 1

[[main]]
name = "Speaking"
pageRef = "speaking"
weight = 3

[[main]]
name = "Music"
pageRef = "music"
weight = 4

[[main]]
name = "TIL"
pageRef = "til"
weight = 2

[[footer]]
name = "About This Site"
pageRef = "about/page"
identifier = "9ZEIG7GoKx"
weight = 2

[[footer]]
name = "About Me"
pageRef = "about/author/"
identifier = "n0HQrcAxys"
weight = 1

[[footer]]
name = "Suggest an Edit"
pageRef = "suggest-edits"
identifier = "WjOIEnILLW"
weight = 9999
[[footer]]
name = "Terms of Use"
pageRef = "terms"
identifier = "terms"
weight = 3

