[[main]]
name = "Blog"
pageRef = "posts"
identifier = "9ZEIG7GoKx"
weight = 9997

[[main]]
name = "Tags"
parent = "More"
pageRef = "tags"
weight = 1

[[main]]
name = "Posts"
parent = "More"
pageRef = "posts"
weight = 2

[[main]]
name = "Speaking"
parent = "More"
pageRef = "speaking"
weight = 3

[[main]]
name = "Music"
parent = "More"
pageRef = "music"
weight = 4

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/3sztof/"
identifier = "dYA273SzWc"
weight = 1

[[main]]
pre = "github"
url = "https://github.com/3sztof"
identifier = "CldNYTp7MY"
weight = 2

[[main]]
pre = "envelope"
url = "mailto:krzysztof.wilczynski@protonmail.com"
identifier = "GN370nTLK7"
weight = 3

[[footer]]
name = "About This Site"
pageRef = "about/page"
identifier = "9ZEIG7GoKx"
weight = 2

[[footer]]
name = "About Me"
pageRef = "about/author/"
identifier = "n0HQrcAxys"
weight = 1

[[footer]]
name = "Suggest an Edit"
pageRef = "suggest-edits"
identifier = "WjOIEnILLW"
weight = 9999
