colorScheme = "marvel"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
smartTOC = true
mainSections = ["posts"]

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "hero"
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "default"

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = true
showWordCount = true
showZenMode = true

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = true
showLikes = true
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = true
cardView = true
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyC1Y4jJzt8_NTyRYWesmTHxmBCjG4ITams"
authDomain = "github-io-personal-page.firebaseapp.com"
projectId = "github-io-personal-page"
storageBucket = "github-io-personal-page.firebasestorage.app"
messagingSenderId = "941309870811"
appId = "1:941309870811:web:abf616c88f2efe0158c2fe"
measurementId = "G-811WVKSKN1"

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]
identifier = "3sztof"
globalWidget = true
globalWidgetColor = ""
globalWidgetPosition = "Right"

[verification]

[rssnext]
